language: node_js
node_js: node
cache:
  directories:
    - node_modules
services:
  - postgresql
before_script:
  - psql -c 'create database testdb;' -U postgres
  - psql -c "CREATE USER ayebare WITH PASSWORD '123';" -U postgres
script:
  - npm install
  - npm test
after_success:
  - npm run coverage
